### ISSUE TITLE
🐛 [Bug]There is a bug in the captain assignment

### ISSUE THREAD

**Issue by zhwblm** [vmangos/core#1930] opened 2023-06-05 01:46 UTC
There is a problem with the allocation of the captain in the VMANGOS squadron, if the captain distributes the loot instead, then regardless of the quality of the item, only the captain can see it, and the other team members cannot see the pickup, and the normal captain allocation should be equal to or higher than the selected quality of the item is the captain allocation At the same time, all team members should be able to view the corpse But in the latest Vmangos it is wrong
### Expected behavior

  Client Version:
  - 1.12.1.5875

-->

  Operating System:
  - Win 10

**Comment by NickTyrer** [comment] 2023-06-28 15:11
Duplicate of #1897

**Closed as completed** 2023-06-28 15:11 UTC
Labels: bug
