### ISSUE TITLE
🐝 [Bug]Bride of the Embalmer

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2420] opened 2024-01-09 02:45 UTC
## 🐝 Bug report - Quest
![image](https://github.com/vmangos/core/assets/58101246/7dafb30e-391c-45ac-9b80-dd7a2b0d47dc)

Eliza's guards she spawns get stuck and evade on spawn, never being able to reach their target.

### Expected behavior
Shouldn't evade on spawn

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 1.12.1.5875

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by ratkosrb** [comment] 2024-01-09 16:35
I can't reproduce the issue. The guards chase and attack me properly.

**Comment by ShiyoKozuki** [comment] 2024-01-09 16:38
> I can't reproduce the issue. The guards chase and attack me properly.

They got stuck in the grave for me and didn't follow.

**Comment by ratkosrb** [comment] 2024-01-09 16:42
But they don't even get spawned on the grave, they spawn next to Eliza.

**Comment by ShiyoKozuki** [comment] 2024-01-09 17:02
> But they don't even get spawned on the grave, they spawn next to Eliza.

You can see in my screenshot they spawned on the grave and were spam evading. They even struggled to stay hitting me inside their hit boxes in melee range, and kept evading.

**Comment by ratkosrb** [comment] 2024-01-09 17:06
I tested it and it didn't happen. I spawned her twice, and both times the guards spawned around her not on the grave, and they did not bug out.

**Comment by ShiyoKozuki** [comment] 2024-01-09 17:22
Did you try moving the position of the ghouls onto the grave like in the screenshot and then see if them being there causes their navmesh to fail and to spam evade because the terrain is invalid / missing navmesh?
They probably spawn at a random pos, and you'd need to respawn her infinite amount of times to get them to spawn directly on the grave. So the easiest solution is to put the mobs on the spot that evade bugging happened, as that spot is the issue, not the quest itself.

**Comment by ratkosrb** [comment] 2024-01-09 18:04
It sounds like a one off to me. I'm closing the issue as the mobs work fine for me. Nobody is gonna try infinite times to reproduce your issue, and I don't know what you expect to be done about it either. Not going to disable pathfinding for the mobs and let them walk in straight lines...

**Closed as completed by ratkosrb** 2024-01-09 18:04 UTC
Labels: bug, quest
