### ISSUE TITLE
🐛 [Bug] lost keybinds 

### ISSUE THREAD

**Issue by coderAt30** [vmangos/core#2584] opened 2024-04-14 16:07 UTC
first login
i set my custom keybinds.quit

second login
my custom keybinds exists.  it''s ok

third login
my keybinds all lost.

It puzzlesme for a long time.
help!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ratkosrb** [comment] 2024-04-14 16:37
Duplicate of https://github.com/vmangos/core/issues/2578

**Closed as completed by ratkosrb** 2024-04-14 16:37 UTC
Labels: bug

**Comment by coderAt30** [comment] 2024-04-15 04:13
> Duplicate of #2578

could you help me ?

**Comment by Wall-core** [comment] 2024-04-15 04:25
It's because you're either logging in to other servers or other characters. Keybinds are stored serverside and cached by the client. This means that when you log in to a character, if the keybinds aren't cached then they won't be active. What you can do is simply open the keybind menu, and immediately close it. This will cause the client to cache the settings from the server.

This is not a bug or an issue though. This is working correctly as intended.

**Comment by coderAt30** [comment] 2024-04-15 04:52
> It's because you're either logging in to other servers or other characters. Keybinds are stored serverside and cached by the client. This means that when you log in to a character, if the keybinds aren't cached then they won't be active. What you can do is simply open the keybind menu, and immediately close it. This will cause the client to cache the settings from the server.
> 
> This is not a bug or an issue though. This is working correctly as intended.

thank you for answering me. but i can not understand it.
this issue don not happen with me only.  it happens with the players who plays   in my server
does vmangos have the funtion of storing the keybinds serverside?  which table and column?

**Comment by Wall-core** [comment] 2024-04-15 04:55
check the character_action table

**Comment by coderAt30** [comment] 2024-04-15 04:57
> check the character_action table

this issue don not happen with me only. it happens with the players who play in my server

**Comment by coderAt30** [comment] 2024-04-15 05:05
> check the character_action table

thank you  .     maybe  character_action table 's data is lost.
