### ISSUE TITLE
Explosive Sheep has infinite cooldown time 🐛 [Bug]

### ISSUE THREAD

**Issue by felixq** [vmangos/core#1267] opened 2021-07-04 21:09 UTC
When used it has an infinite cooldown time and you cannot use the sheep or any explosive or grenade again. You have to leave and re-enter to be able to use the sheep or a grenade again. 

It should be able to be used again a minute later. 
https://classicdb.ch/?item=4384

  Client Version:
  - 1.12.1.5875

**Comment by NickTyrer** [comment] 2021-07-05 06:26
Duplicate of  #1231

**Closed as completed by NickTyrer** 2021-07-05 06:26 UTC
Labels: bug
