### ISSUE TITLE
🐛 [Bug]Crushridge Warmonger AI/spells

### ISSUE THREAD

**Issue by ShiyoKozuki** [vmangos/core#2357] opened 2023-12-19 06:22 UTC
## 🐛 Bug report
Crushridge Warmongers "call for help" then immediately enrage and say "Goes into a rage after seeing a friend fall in battle!" and gains an enrage effect even if they are alone and no ogre was killed.

![image](https://github.com/vmangos/core/assets/58101246/272d3c9c-f3af-45cc-970b-47f83ddcb168)

### Expected behavior
Unsure how they should work, but going into enrage due to a friend falling in battle when no friend actually fell in battle seems incorrect.

### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version:  1.12.1

Commit Hash:  newest

OS Client:  win10
OS Server:  win10

### Crashlog

- None

**Comment by mserajnik** [comment] 2023-12-19 09:55
Duplicate of #1184.

**Closed as completed** 2023-12-19 10:16 UTC
Labels: bug
