### ISSUE TITLE
🔧 [Support]Message: Failed to find target for script with id 852401

### ISSUE THREAD

**Issue by Yuhenan** [vmangos/core#1808] opened 2023-02-17 17:21 UTC
Hi,

I have updated from https://github.com/vmangos/core/commit/62fd507cf2afedb9105f6687cc7ad51446bebd05 to https://github.com/vmangos/core/commit/f08657d2037116b4cf7201ff892c91f79e4ef500 (current development branch).

After starting the server i get the following messages in the server output:

---------------------------------------------------------------------------------------------------------------------------------------
FindScriptTargets: Failed to find target for script with id 852401 (target_param1: 0), (target_param2: 0), (target_type: 1) 

ERROR: FindScriptTargets: Failed to find target for script with id 57020 (target_param1: 5728), (target_param2: 30), (target_type: 8).
ERROR: FindScriptTargets: Failed to find target for script with id 141302 (target_param1: 1414), (target_param2: 10), (target_type: 8).

ERROR: SCRIPT_COMMAND_TALK (script id 243527) call for a nullptr or non-worldobject source (TypeId: 0), skipping.
-----------------------------------------------------------------------------------------------------------------------------------------
Expected behavior
No messages

Steps to reproduce
just start the server, but it takes some time - sometimes up to 1-2h hours

**Comment by NickTyrer** [comment] 2023-08-06 13:57
Duplicate of https://github.com/vmangos/core/issues/1496

**Closed as completed by NickTyrer** 2023-08-06 13:57 UTC
Labels: support
