### ISSUE TITLE
🦂 [Bug] Molten Core Runes Missing/Defective

### ISSUE THREAD

**Issue by cpevors** [vmangos/core#2097] opened 2023-07-17 01:47 UTC
## 🦂 Bug report - Dungeon
The "runes of warding" near most bosses in Molten Core, which must be doused with an Aqual or Eternal Quintessence, are either missing (and appear as gaping holes in the ground) or are non-functional (i.e. they have the swirling fire animation but cannot be doused with a quintessence). As such, Majordomo Executus never spawns, one cannot summon Ragnaros, etc. 

![Screenshot 2023-07-16 213723](https://github.com/vmangos/core/assets/139099164/ea522ed9-fae1-4cf6-a8d8-c316e8f77cb5)

![Screenshot 2023-07-16 214253](https://github.com/vmangos/core/assets/139099164/e5f95c1c-2b95-4195-9913-e09fb4f73a86)

### Expected behavior
The runes next to bosses should both exist (and appear like the rune in this screenshot), and should be extinguishable after a boss is killed with a quintessence. Once all the runes are doused, Majordomo Executus should spawn on the peninsula above the Sulfuron Harbinger. 

![55066576-5f827f80-507e-11e9-831b-c9e1ee47f8eb](https://github.com/vmangos/core/assets/139099164/30944916-cff0-4b05-9674-0cc976edf825)

### Steps to reproduce

1. .tele MoltenCore, and .additem 17333 to add an Aqual Quintessence to your bags.
2. Run to a boss that has a rune (e.g. Magmadar, Gehennas, etc.)
3. Kill boss, and attempt to use the Quintessence on the rune.
4. ...
5. Profit

### Version & Environment
I tested this across all ten patch options in the config file. This problem persists across all patch options within the project.
  Client Version:
  - 1.12.1.5875
  - 1.11.2.5464
  - 1.10.2.5302
  - 1.9.4.5086
  - 1.8.4.4878
  - 1.7.1.4695
  - 1.6.1.4544
  - 1.5.1.4449
  - 1.4.2.4375
  - 1.3.1.4297
  - 1.2.4.4222

  Operating System:
  - Win 11
OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Daribon** [comment] 2023-07-17 11:20
I can't reproduce it. The runes exist for me.
![WoW_z90EyhVkzw](https://github.com/vmangos/core/assets/6137576/17f18bb7-172d-4ea4-842c-7ad0c796dd10)

Please state which commit your server is running on.

**Comment by cpevors** [comment] 2023-07-17 11:21
I’m not home at the moment to give the version number, but I pulled down the latest commits yesterday afternoon around 17:00 EST, so I believe my commits are up to date as of 16 July 2023.

**Comment by Daribon** [comment] 2023-07-17 11:25
Then its related to this this commit:
https://github.com/vmangos/core/blob/f9e4ccbf92b69d57e52588eb46ff13d6d41bf3a6/sql/migrations/20230713165825_world.sql#L20
@NickTyrer
It deletes not only Dark Iron Deposits, but also the runes in Molten Core.
For example guid 232212, Rune of Korko or guid 232213, Molten Core Circle BARON

**Comment by cpevors** [comment] 2023-07-17 11:28
Oi. Thanks for looking into it so promptly, and for confirming that I’m not totally daft. 

Hopefully the removal of the runes gets reversed.

**Comment by NickTyrer** [comment] 2023-07-17 13:43
Closed in #2098

**Closed as completed by NickTyrer** 2023-07-17 13:43 UTC
Labels: bug, dungeon

**Comment by cpevors** [comment] 2023-07-18 00:00
While the migration fix removes scripts that remove the runes from the raid instance, I want to point out that pulling down and loading the commit does not add them back. I had to drop my mangos/core database and completely rebuild it, in order to get the runes to appear in the instance.
