### ISSUE TITLE
Turning in Scourgestones should grant experience points.

### ISSUE THREAD

**Issue by tonymmm1** [vmangos/core#464] opened 2020-04-16 05:23 UTC
**Current behavior**: 
Turning in Scourgestones in Western Plaguelands does not grant experience points. 
**Expected behavior**: 
There should be around 560 xp per turn in as reference to https://classic.wowhead.com/item=12844/argent-dawn-valor-token.
**Steps to reproduce**

**Client version**: 
1.12.1
**Commit hash**: 
https://github.com/vmangos/core/commit/85ac39fd5485f68496e7c33d796abb2e5f3ddbf9
**Operating system**: 
Linux 64 bit

**Comment by tonymmm1** [comment] 2020-05-07 05:28
Some useful information
Patch 1.3.0+

Creatures:
10840 Argent Officer Pureheart(Alliance)
10839 Argent Officer Garush(Horde)

Quests:
5408 Minion's Scourgestones
5508 Corruptors' Scourgestones
5509 Invader's Scourgestones
5402 Minion's Scourgestones
5403 Invader's Scourgestones
5404 Corruptor's Scourgestones
5406 Corruptor's Scourgestones
5510 Minion's Scourgestones 

Min level 50

Objectives:
20 x [Type] Scourgestones

Rewards:
1 x Argent Dawn Valor Token
Exp. 560

**Comment by NickTyrer** [comment] 2021-06-17 09:39
Closing, database entries are correct for these quests. I think the issue is related to #1211.

**Closed as completed by NickTyrer** 2021-06-17 09:39 UTC
Labels: bug, quest
