### ISSUE TITLE
🐛 [Bug] ERROR: FindScriptTargets

### ISSUE THREAD

**Issue by 418451** [vmangos/core#1816] opened 2023-02-26 12:54 UTC
2023-02-26 20:04:14 SERVER STARTUP TIME: 0 minutes 10 seconds
2023-02-26 20:04:14 mangosd process priority class set to HIGH
2023-02-26 20:04:14 
2023-02-26 20:04:14 >> Only expired mails (need to be return or delete) or DB table `mail` is empty.
2023-02-26 20:04:14 Max allowed socket connections 1024
2023-02-26 20:05:01 GameEvent 13 "Elemental Invasion" removed.
2023-02-26 20:05:01 GameEvent 67 "Dwarven Mortar Team (Dun Morogh)" removed.
2023-02-26 20:05:01 Next game event check in 888 seconds.
2023-02-26 20:19:49 GameEvent 152 "Southshore Assassins" started.
2023-02-26 20:19:49 Next game event check in 2100 seconds.
2023-02-26 20:43:28 ERROR: FindScriptTargets: Failed to find target for script with id 852401 (target_param1: 0), (target_param2: 0), (target_type: 1).
2023-02-26 20:45:06 ERROR: FindScriptTargets: Failed to find target for script with id 852401 (target_param1: 0), (target_param2: 0), (target_type: 1).
2023-02-26 20:50:50 ERROR: FindScriptTargets: Failed to find target for script with id 852401 (target_param1: 0), (target_param2: 0), (target_type: 1).

**Comment by NickTyrer** [comment] 2023-08-06 13:57
Duplicate of https://github.com/vmangos/core/issues/1496

**Closed as completed by NickTyrer** 2023-08-06 13:57 UTC
Labels: bug
