### ISSUE TITLE
H:\Github\vmangos\src\game\Objects\Object.cpp:982: Error: Assertion in Object::SetUInt64Value failed: index + 1 < m_valuesCount || PrintIndexError(index, true)

### ISSUE THREAD

**Issue by wthslw001** [vmangos/core#143] opened 2019-02-12 15:26 UTC
_What does this error message mean?_

2019-02-12 23:12:11 H:\Github\vmangos\src\game\Objects\Object.cpp:982: Error: Assertion in Object::SetUInt64Value failed: index + 1 < m_valuesCount || PrintIndexError(index, true)
2019-02-12 23:12:11 Item::WakeUp()+0x5a8 [0x2b74b8]
Player::_LoadInventory()+0x650 [0xf68e0]
Player::LoadFromDB()+0x1719 [0xd47c9]
WorldSession::HandlePlayerLogin()+0x1ad [0x3c5a4d]
WorldSession::HandlePlayerLogin()+0x113d [0x3c69dd]
BarGoLink::step()+0x1e6d [0x519d2d]
CreatureAI::SwitchAiAtControl()+0xa68 [0x416d8]
SpellAuraHolder::GetTarget()+0x4661 [0x304c1]
BarGoLink::step()+0xd21 [0x518be1]
ACE_OS_Thread_Adapter::invoke()+0xa8 [0x6e1d8]
o_exp()+0x5a [0x203ba]
BaseThreadInitThunk()+0x14 [0x181f4]
RtlUserThreadStart()+0x21 [0x6a251]

![image](https://user-images.githubusercontent.com/8679316/52645945-c14ab800-2f1c-11e9-9f33-9f788998ba12.png)

**Comment by ratkosrb** [comment] 2019-02-12 15:31
Duplicate of https://github.com/vmangos/core/issues/142 !

**Closed as completed by ratkosrb** 2019-02-12 15:31 UTC
