### ISSUE TITLE
Transmute: Arcanite/Mooncloth/Salt Shaker CD bug

### ISSUE THREAD

**Issue by zealtla** [vmangos/core#315] opened 2019-11-26 18:00 UTC
**Current behavior**: 

**Expected behavior**: 

**Steps to reproduce**:

1. if players change map ,reset dungeons or enter dungeons the cd will be reset
2. 
3. 

**Client version**: 
1.12.3（6141）
**Commit hash**: 

**Operating system**: 
windows10

**Comment by zealtla** [comment] 2019-11-27 08:17
after player cast Transmute: Arcanite/Mooncloth/Salt Shaker,then use Hearthstone，those spells's cd will be bug

**Comment by ratkosrb** [comment] 2019-11-27 16:10
I cannot reproduce the issue.
https://streamable.com/xjadn

**Comment by coolzoom** [comment] 2019-11-29 14:22
I cannot reproduce the issue.

**Comment by zealtla** [comment] 2019-11-30 15:57
step1:cast&nbsp;Transmute: Arcanite,cd time is 2 days

step2:use hearthstone (entry:6948) go home,then cd time was 1 min...

if use teleport npc to tele another map,Transmute: Arcanite spell cd will be bug too
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"coolzoom"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月29日(星期五) 晚上10:22
收件人:&nbsp;"vmangos/core"<core@noreply.github.com&gt;;
抄送:&nbsp;"螃蟹"<871430185@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vmangos/core] Transmute: Arcanite/Mooncloth/Salt Shaker CD bug (#315)




I cannot reproduce the issue.

**Comment by zealtla** [comment] 2019-12-02 08:11
Those spells cd time will bugged when player use hearthstone or tele npc tele to another map or dungeons,I am sure,u guys can try it.

**Comment by ratkosrb** [comment] 2019-12-02 16:32
@zealtla Watch the video: https://streamable.com/3535s
Cooldown is not reset after teleporting.

**Comment by ratkosrb** [comment] 2020-03-26 16:04
Closing this since it is not reproducable.

**Closed as completed by ratkosrb** 2020-03-26 16:04 UTC
