### ISSUE TITLE
Troll racial "Berserking" seems bugged

### ISSUE THREAD

**Issue by mikemenasi** [vmangos/core#663] opened 2020-07-06 14:37 UTC
**Current behavior**: 
The in-game description is pretty clear: 10% to 30% attack and spellcasting speed based on how badly you are injured.

However, when I tried it out during yesterday's stress test, it reduced my attack speed from 2 to 1.54 while I was at 20% hp, which is about 23% haste - quite weaker than the supposed 30% which should bring it down to 1.4. My casting speed was reduced from 1.5 to 1.15, which is also about 23-24% haste.

see https://forum.gurubashi.org/viewtopic.php?f=8&t=48&sid=79f204070c319dc221bfff5fb5504174

**Client version**: 
1.12.1
**Commit hash**: 
5a13b14 
**Operating system**: 
Win

**Comment by ratkosrb** [comment] 2020-07-06 14:47
Vmangos is in no way affiliated with the private server you linked. Please compile the latest core yourself and test things locally. I cannot possibly know what modifications have been made on anyone's private server and how old is the revision they based it on. Don't just link the most recent commit if you are not a staff member of said server and know the exact revision. And to verify how things should work in 1.12, test them on the official Classic servers and compare the behavior with vmangos results, rather than speculate based on a tooltip.

**Comment by GrenderG** [comment] 2020-07-06 16:32
Can confirm this is happening in latest vMaNGOS, although the [value is clearly set to 30](https://github.com/vmangos/core/blob/9f24cc80452ef7c0264c4543eca1887d8bfd3f81/src/game/Spells/SpellEffects.cpp#L1604). Gonna investigate this.

**Comment by GrenderG** [comment] 2020-07-06 19:48
Working as intended. Tested in Classic and the values are the same, max 1.54 with 2.0 speed. You can close this Issue, @ratkosrb.

**Closed as completed** 2020-07-06 19:50 UTC

**Comment by Gamemechanicwow** [comment] 2020-07-06 20:26
I know this is closed, but let me clarify this misunderstanding. You are calculating haste wrong. 30% haste doesn't reduce your swingtime by 30%. 30% haste increases the number of swings/casts you can perform by 30%.

attack speed 2 = 30 swings pr minute
30% more attacks = 39 swings pr minute (30*1,3)
39 swings pr minute = 1.5384... attack speed

**Comment by GrenderG** [comment] 2020-07-06 20:27
> I know this is closed, but let me clarify this misunderstanding. You are calculating haste wrong. 30% haste doesn't reduce your swingtime by 30%. 30% haste increases the number of swings/casts you can perform by 30%.
> 
> attack speed 2 = 30 swings pr minute
> 30% more attacks = 39 swings pr minute (30*1,3)
> 39 swings pr minute = 1.5384... attack speed

Thanks for the clarification. :+1:

**Comment by ST369** [comment] 2022-06-29 21:24
Tooltip of the mana (caster) version of Berserking is misleading. It reduces cast time by 10-30%.
So ×0.7 instead of ÷1.3 (at maximum effect)
Classic players have been reporting higher speed increase than expected (10-43%) ... 1.43⁻¹ = 0.7
It's not working correctly on vmangos.
https://classic.wowhead.com/spell=20554/berserking
