### ISSUE TITLE
Use the flag to enter the battle, but no creature can be seen.

### ISSUE THREAD

**Issue by gamelgs** [vmangos/core#565] opened 2020-05-23 07:54 UTC
QUEST  <The Challenge>    QUEST ID 9015

Theldren creature id   16059
  
Banner of Provocation          ITEM ID 21986

Use it to reproduce.

Theldren didn't show up.

**Client version**: 
1.12.1
**Commit hash**: 
d5ac534c57c7204599ad400fa4889768d7de89b7
**Operating system**: 
win10

**Comment by ulfgebhardt** [comment] 2021-01-01 19:09
@gamelgs could you provide a more detailed repro and include some screenshots of the problem so it becomes easier to undnerstand? <3

**Comment by ratkosrb** [comment] 2021-01-01 23:23
Looks like duplicate of https://github.com/vmangos/core/issues/818

**Comment by ulfgebhardt** [comment] 2021-01-05 08:46
Closing this since #818 seem to have have fixed remaining Issues.

**Closed as completed by ulfgebhardt** 2021-01-05 08:46 UTC
Labels: bug, quest
