### ISSUE TITLE
 Mage Frostbite talent spell breaks instantly after its poping.🐞 [Bug]

### ISSUE THREAD

**Issue by Alller** [vmangos/core#1601] opened 2022-09-03 11:00 UTC
### Steps to reproduce

1.
2.
3.
4. ...
5. Profit

### Version & Environment

Client Version: 

Commit Hash:  

OS Client: 
OS Server: 

### Crashlog

- None

**Comment by Alller** [comment] 2022-09-03 11:17
https://user-images.githubusercontent.com/112757757/188267989-9e1af05f-83b1-40e1-bf5d-d9981d150c50.mp4

**Comment by natrist** [comment] 2022-10-04 22:35
Can you please elaborate on the issue and the steps needed to reproduce it? Thank you.

**Comment by ratkosrb** [comment] 2022-10-05 01:39
I think this report is from the Everlook private server, and not a clean vmangos. Wall talked to me about it before and I was unable to reproduce it myself.

**Comment by natrist** [comment] 2022-10-05 10:59
Can we tag it as such and close the issue?

**Closed as completed** 2022-10-31 07:32 UTC
Labels: bug, spell
